package io.foojay.support;

import java.util.Collections;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JLabel;

public class QuickPanel extends javax.swing.JPanel {

    public QuickPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        versions = new javax.swing.JSlider();
        autoInstallJDK = new javax.swing.JRadioButton();
        manualJDK = new javax.swing.JRadioButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.jLabel1.text")); // NOI18N

        versions.setMaximum(20);
        versions.setMinimum(8);
        versions.setPaintLabels(true);
        versions.setPaintTicks(true);
        versions.setSnapToTicks(true);
        versions.setValue(15);

        buttonGroup1.add(autoInstallJDK);
        autoInstallJDK.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(autoInstallJDK, org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.autoInstallJDK.text")); // NOI18N
        autoInstallJDK.setToolTipText(org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.autoInstallJDK.toolTipText")); // NOI18N

        buttonGroup1.add(manualJDK);
        org.openide.awt.Mnemonics.setLocalizedText(manualJDK, org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.manualJDK.text")); // NOI18N
        manualJDK.setToolTipText(org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.manualJDK.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versions, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autoInstallJDK)
                            .addComponent(manualJDK))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(versions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoInstallJDK)
                .addGap(12, 12, 12)
                .addComponent(manualJDK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton autoInstallJDK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton manualJDK;
    private javax.swing.JSlider versions;
    // End of variables declaration//GEN-END:variables

    void setVersions(List<Integer> jdks, Integer value) {
        Hashtable<Integer, JLabel> labels = new Hashtable<>();
        for(Integer v : jdks) {
            labels.put(v, new JLabel(String.valueOf(v)));
        }
        versions.setMaximum(Collections.max(jdks));
        versions.setLabelTable(labels);
        versions.setValue(value);
    }
}
